//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer
    {
        public customer()
        {
            this.deliveryorder = new HashSet<deliveryorder>();
            this.deposit_receipt = new HashSet<deposit_receipt>();
        }
    
        public int Customerid { get; set; }
        public string customername { get; set; }
        public string CustomerAddress { get; set; }
        public string District { get; set; }
        public int PhoneNumber { get; set; }
    
        public virtual ICollection<deliveryorder> deliveryorder { get; set; }
        public virtual ICollection<deposit_receipt> deposit_receipt { get; set; }
    }
}
