//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class defect_item
    {
        public int defectID { get; set; }
        public string itemName { get; set; }
        public int itemQuantity { get; set; }
        public double returnPrice { get; set; }
        public string employeeID { get; set; }
    
        public virtual empolyee empolyee { get; set; }
    }
}
