//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class deliveryorder
    {
        public deliveryorder()
        {
            this.deliverynote = new HashSet<deliverynote>();
            this.deliveryorderproduct = new HashSet<deliveryorderproduct>();
            this.installationrequest = new HashSet<installationrequest>();
        }
    
        public int deliveryid { get; set; }
        public Nullable<System.DateTime> docreatedate { get; set; }
        public string deliverystatus { get; set; }
        public Nullable<System.DateTime> expectdeliverydate { get; set; }
        public Nullable<int> timeslot { get; set; }
        public Nullable<System.DateTime> deliverycompleteDate { get; set; }
        public string EmpID { get; set; }
        public int Customerid { get; set; }
        public string InstallationNeed { get; set; }
    
        public virtual customer customer { get; set; }
        public virtual ICollection<deliverynote> deliverynote { get; set; }
        public virtual empolyee empolyee { get; set; }
        public virtual ICollection<deliveryorderproduct> deliveryorderproduct { get; set; }
        public virtual ICollection<installationrequest> installationrequest { get; set; }
    }
}
