//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class deliverynote
    {
        public int deliverynoteid { get; set; }
        public int deliveryid { get; set; }
        public byte[] deliverysignature { get; set; }
    
        public virtual deliveryorder deliveryorder { get; set; }
    }
}
