//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class deliveryorderproduct
    {
        public int dopid { get; set; }
        public int buyqty { get; set; }
        public int deliveryid { get; set; }
        public int productid { get; set; }
        public Nullable<float> amount { get; set; }
    
        public virtual deliveryorder deliveryorder { get; set; }
        public virtual product product { get; set; }
    }
}
