//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class empolyee
    {
        public empolyee()
        {
            this.deliveryorder = new HashSet<deliveryorder>();
            this.electronic_purchase_order = new HashSet<electronic_purchase_order>();
            this.goods_returned_note = new HashSet<goods_returned_note>();
            this.installationrequest = new HashSet<installationrequest>();
            this.inventory_level = new HashSet<inventory_level>();
            this.payment = new HashSet<payment>();
            this.re_order_requests = new HashSet<re_order_requests>();
            this.replenishment_request = new HashSet<replenishment_request>();
            this.defect_item = new HashSet<defect_item>();
            this.products = new HashSet<product>();
        }
    
        public string EmpID { get; set; }
        public string EmpName { get; set; }
        public string Empdepartment { get; set; }
        public string account_number { get; set; }
        public string password { get; set; }
        public string security_question_answer { get; set; }
    
        public virtual ICollection<deliveryorder> deliveryorder { get; set; }
        public virtual ICollection<electronic_purchase_order> electronic_purchase_order { get; set; }
        public virtual ICollection<goods_returned_note> goods_returned_note { get; set; }
        public virtual ICollection<installationrequest> installationrequest { get; set; }
        public virtual ICollection<inventory_level> inventory_level { get; set; }
        public virtual ICollection<payment> payment { get; set; }
        public virtual ICollection<re_order_requests> re_order_requests { get; set; }
        public virtual ICollection<replenishment_request> replenishment_request { get; set; }
        public virtual ICollection<defect_item> defect_item { get; set; }
        public virtual ICollection<product> products { get; set; }
    }
}
