//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class goods_received_note
    {
        public string Goods_Received_Note_Number { get; set; }
        public Nullable<System.DateTime> Receipt_Date { get; set; }
        public string ItemName { get; set; }
        public string ItemType { get; set; }
        public string ItemBrand { get; set; }
        public string ItemQuantity { get; set; }
        public string ItemPrice { get; set; }
        public Nullable<double> Amounts { get; set; }
        public string Buyer_Signature { get; set; }
        public string EPOrderID { get; set; }
        public string SupplierName { get; set; }
    
        public virtual electronic_purchase_order electronic_purchase_order { get; set; }
        public virtual supplier supplier { get; set; }
    }
}
