//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class installationrequest
    {
        public int installRequestid { get; set; }
        public string installEmpID { get; set; }
        public Nullable<System.DateTime> installDate { get; set; }
        public Nullable<System.DateTime> installComDate { get; set; }
        public Nullable<int> installTimeslot { get; set; }
        public string installStatus { get; set; }
        public byte[] installSignImage { get; set; }
        public int deliveryid { get; set; }
    
        public virtual deliveryorder deliveryorder { get; set; }
        public virtual empolyee empolyee { get; set; }
    }
}
