//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class better_limitedEntities : DbContext
    {
        public better_limitedEntities()
            : base("name=better_limitedEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<customer> customer { get; set; }
        public DbSet<deliverynote> deliverynote { get; set; }
        public DbSet<deliveryorder> deliveryorder { get; set; }
        public DbSet<deliveryorderproduct> deliveryorderproduct { get; set; }
        public DbSet<deposit_receipt> deposit_receipt { get; set; }
        public DbSet<electronic_purchase_order> electronic_purchase_order { get; set; }
        public DbSet<empolyee> empolyee { get; set; }
        public DbSet<goods_received_note> goods_received_note { get; set; }
        public DbSet<goods_returned_note> goods_returned_note { get; set; }
        public DbSet<installationrequest> installationrequest { get; set; }
        public DbSet<inventory_level> inventory_level { get; set; }
        public DbSet<payment> payment { get; set; }
        public DbSet<payment_receipt> payment_receipt { get; set; }
        public DbSet<purchase_order_detail> purchase_order_detail { get; set; }
        public DbSet<re_order_requests> re_order_requests { get; set; }
        public DbSet<reorderingitem> reorderingitem { get; set; }
        public DbSet<replenishment_request> replenishment_request { get; set; }
        public DbSet<supplier> supplier { get; set; }
        public DbSet<defect_item> defect_items { get; set; }
        public DbSet<product> products { get; set; }
    }
}
