//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public product()
        {
            this.deliveryorderproducts = new HashSet<deliveryorderproduct>();
            this.deposit_receipt = new HashSet<deposit_receipt>();
            this.payment_receipt = new HashSet<payment_receipt>();
        }
    
        public int productid { get; set; }
        public string productname { get; set; }
        public string productType { get; set; }
        public string productbrand { get; set; }
        public float productweight { get; set; }
        public int productUnitQty { get; set; }
        public double productUnitprice { get; set; }
        public int StockMaxNumber { get; set; }
        public string EmpID { get; set; }
    
        public virtual ICollection<deliveryorderproduct> deliveryorderproducts { get; set; }
        public virtual ICollection<deposit_receipt> deposit_receipt { get; set; }
        public virtual empolyee empolyee { get; set; }
        public virtual ICollection<payment_receipt> payment_receipt { get; set; }
    }
}
