//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class reorderingitem
    {
        public int ReOrderID { get; set; }
        public string ItemName { get; set; }
        public string ItemType { get; set; }
        public string ItemBrand { get; set; }
        public string Supplier { get; set; }
        public Nullable<short> ItemQuantity { get; set; }
        public Nullable<double> ItemPrice { get; set; }
        public Nullable<double> Amounts { get; set; }
        public Nullable<System.DateTime> ReceiveDate { get; set; }
    
        public virtual supplier supplier1 { get; set; }
    }
}
