//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class replenishment_request
    {
        public string ReplenishmentID { get; set; }
        public string ItemName { get; set; }
        public string ItemType { get; set; }
        public string ItemBrand { get; set; }
        public Nullable<short> ItemQuantity { get; set; }
        public string Store_Address { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public string Delivery_Address { get; set; }
        public string Remarks { get; set; }
        public string EmpID { get; set; }
    
        public virtual empolyee empolyee { get; set; }
    }
}
