//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class supplier
    {
        public supplier()
        {
            this.goods_received_note = new HashSet<goods_received_note>();
            this.purchase_order_detail = new HashSet<purchase_order_detail>();
            this.reorderingitem = new HashSet<reorderingitem>();
        }
    
        public string SupplierName { get; set; }
        public string SupplierPhoneNumber { get; set; }
        public string SupplierEmail { get; set; }
        public string SupplierAddress { get; set; }
        public string SupplierOther { get; set; }
    
        public virtual ICollection<goods_received_note> goods_received_note { get; set; }
        public virtual ICollection<purchase_order_detail> purchase_order_detail { get; set; }
        public virtual ICollection<reorderingitem> reorderingitem { get; set; }
    }
}
